
const defaultPropertyValueMap = new Map([
    ['font-weight','400'],
    ['font-variant','normal'],
    ['font-style','normal'],
    ['letter-spacing','normal'],
    ['line-height','normal'],
    ['text-decoration','none'],
    ['text-align','start'],
    ['text-indent','0px'],
    ['text-transform','none'],
    ['vertical-align','baseline'],
    ['white-space','normal'],
    ['word-spacing','normal'],
    //Color And Background Stuff
    ['background-color','transparent'],
    ['background-attachment','scroll'],
    ['background-image','none'],
    // Background stuff
    ['background-position',''],
    ['background-repeat','repeat'],
    ['border-top-style', 'none'],
    ['margin','0 0 0 0'],
    ['padding','0 0 0 0'],
    ['min-height','0px'],
    ['max-height','none'],
    ['min-width','0px'],
    ['max-width','none'],
    // Positioning 
    ['position','static'],
    ['top','auto'],
    ['bottom','auto'],
    ['right','auto'],
    ['left','auto'],
    ['float','none'],
    ['display'],
    ['clear','none'],
    ['z-index','auto'],
    // Table 
    ['border-collapse','separate'],
    ['border-spacing','0px 0px'],
    ['caption-side','top'],
    ['empty-cells','show'],
    ['table-layout','auto'],
    ['overflow','visible'],
    ['cursor','auto'],
    ['visibility','visible'], 
    ['outline-offset','0px'], 
    ['box-sizing','content-box'], 
    ['resize','none'], 
    ['text-shadow' ,'none'], 
    ['text-overflow' ,'clip'], 
    ['word-wrap' ,'normal'], 
    ['box-shadow','none'],
    ['border-top-left-radius','0px'], 
    ['border-top-right-radius' ,'0px'], 
    ['border-bottom-left-radius' ,'0px'], 
    ['border-bottom-right-radius','0px']
]);